
library identifier: "pipeline-library@issues-11-to-15", retriever: modernSCM(
  [$class: "GitSCMSource",
   remote: "https://github.com/syvanen/pipeline-library.git"])

node ('maven') {
  stage('Code Build') {
      git url: "${SOURCE_CODE_URL}"
      sh "mvn clean install -q"
  }

  stage('Image Build') {
      sh """
        set +x
        rm -rf oc-build && mkdir -p oc-build/deployments
        for t in \$(echo "jar;war;ear" | tr ";" "\\n"); do
          cp -rfv ./target/*.\$t oc-build/deployments/ 2> /dev/null || echo "No \$t files"
        done
      """

      binaryBuild(projectName: "pipeline-library-test", buildConfigName: "spring-rest", artifactsDirectoryName: "oc-build")
  }
}
